flags:
    create_new_project : True # if False, attempt to set an existing project as current
    # @TODO option for sharing projects

fileIO:
    data_directory: C:\Users\rhanes\GitHub\autoBW
    db_edits: import_test.xlsx

project_parameters:
    name: psh_lca
    include_databases: 
    - biosphere3
    - ecoinvent3.7.1 cut-off

foreground_db:
    custom_db_name : newdb
    link_to:
        biosphere3 : name, unit, location, categories
        ecoinvent3.7.1 cut-off : name, unit, location, reference product
    

calculations:
    methods: #define manually or provide search string to pull from DB?
        GWP : accdd0f59a6ea000a2b3fd21bcc93a15
        CED : 71c568f03a3f448cbe3a1620d505b061
    functional_units: # list of dictionaries. Value list is [exchange key, amount in kg]
        ethanol : accdd0f59a6ea000a2b3fd21bcc93a15, 100
        gasoline : accdd0f59a6ea000a2b3fd21bcc93a15, 75
        jet fuel : accdd0f59a6ea000a2b3fd21bcc93a15, 50
        diesel : accdd0f59a6ea000a2b3fd21bcc93a15, 65
        