flags:
    create_new_project : True # if False, attempt to set an existing project as current
    # @TODO option for sharing projects

fileIO:
    data_directory: C:\Users\rhanes\GitHub\autoBW
