project_parameters:
    name: PSH LCA FY23
    include_databases:
    - biosphere3
    - ecoinvent3.8 cut-off

foreground_db:
    name: pshlcafy23
    fg_db_import: inv_import_v10_mid_mix_all.xlsx
    generate_keys: False
    save_db: True
    link_fg_to:
        biosphere3 : name, unit, categories
        ecoinvent3.8 cut-off: name, unit, location, reference product


calculations:
    methods: #define manually or provide search string to pull from DB?
        GWP : accdd0f59a6ea000a2b3fd21bcc93a15
        CED : 71c568f03a3f448cbe3a1620d505b061
    functional_units: # list of dictionaries. Value list is [exchange key, amount in kg]
        ethanol : accdd0f59a6ea000a2b3fd21bcc93a15, 100
        gasoline : accdd0f59a6ea000a2b3fd21bcc93a15, 75
        jet fuel : accdd0f59a6ea000a2b3fd21bcc93a15, 50
        diesel : accdd0f59a6ea000a2b3fd21bcc93a15, 65
